### ISSUE TITLE
Update 'Getting Started' Section with a complete example on how to extract features using Cineast

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cineast#103]
[Wiki Section](https://github.com/vitrivr/cineast/wiki/Getting-Started) + [vitrivr.org](https://vitrivr.org/getting_started.html)

- [ ] Configuration examples on the wiki

**Comment by frankier** [comment]
Ideally this would include those settings for doing extractions on a cluster, for large collections -- which are presumably those collections for which search can be most useful. Here's what I've found out so far:

 * The JSON writer is the recommended writer for extraction on a cluster (see https://github.com/vitrivr/cineast/issues/114 ) 
 * That (perhaps?) external parallelism is needed to make full use of the computing resources on a cluster ( https://github.com/vitrivr/cineast/issues/115 ). There should be some guidance for integrating this.

**Comment by lucaro** [comment]
These are good points, we should put this in the documentation as well.

**Comment by silvanheller** [comment]
@Spiess has updated the wiki
