### ISSUE TITLE
distinct scroll position

### ISSUE THREAD

**Issue by mpas97** [vitrivr/cineast#108]
Actually, all views "share" the same scroll position. So if I scroll down, e.g., the list view and then open the gallery view, I'll directly be at the bottom too. In other words, all "movements" are registered by all views, even those currently not displayed. This is quite annoying, because when you go back to the tab you were before, you first have to look for where you left off.

**Comment by sauterl** [comment]
I guess this is an issue for [VitrivrNG](https://github.com/vitrivr/vitrivr-ng).

I took the liberty to move it accordingly: https://github.com/vitrivr/vitrivr-ng/issues/31

**Comment by mpas97** [comment]
@sauterl Thanks! Indeed that was wrong.
