### ISSUE TITLE
File extension isn't stored anywhere for image sequence objects

### ISSUE THREAD

**Issue by Spiess** [vitrivr/cineast#145]
Since the media object path for image sequences only stores the path of the sequence directory, the file extensions of the individual images aren't stored anywhere. This is a problem in case some image sequences contain `.jpg` files while others contain `.JPG` as in these cases frontends cannot know what file extension to request from the data server. This problem also affects the rare case that file extensions are mixed within an image sequence.

Possible fixes may be:
- A new `ObjectIdGenerator` that also includes the file extension as part of the segment ID
- Requiring all image sequence images in the same collection to have the same file extension
- Adding a new file extension attribute to mediaobjects / segments

**Comment by silvanheller** [comment]
I think we're going for the second option. For videos, we also require a unified format.
