### ISSUE TITLE
Passing Arguments to the Constructor of an Extractor

### ISSUE THREAD

**Issue by cribin** [vitrivr/cineast#146]
Hi,

I would like to pass an argument to the constructor of a class, which implements the Extractor interface. From where and how can I do so?

Best,

Ribin

PS: If it is better to discuss this topic in the vitrivr google group, I would like to do so, but my messages are getting deleted there.

**Comment by lucaro** [comment]
Unless your argument is of the type `Map<String, String>` to encode some configuration parameters, arguments are not supported by the extraction runtime. What would you need this for?

**Comment by cribin** [comment]
For communicating with my machine learning algorithm, I would create a class _MLCommunicator_ in cineast, which would receive the current image path from an extractor class, send the image path to my ML-Predictor and receive a json object back, containing all predicted features for one image. My idea is to create a class implementing the extractor interface for each predicted feature in the json file. So I need a way for the extractor classes to communicate with the _MLCommunicator_ class. I thought about using the singleton pattern, but thought that dependency injection through the constructor would be a cleaner way to solve the problem.

**Comment by lucaro** [comment]
There is currently no dependency injection mechanism for the extraction pipeline. What is the reason why the extraction logic itself cannot be implemented in the extractor class?

**Comment by cribin** [comment]
Since I have planned to create multiple classes for extraction(one for each feature, such as aesthetic score, emotion, etc.), the communication with the ML Predictor would be duplicated in each class. So I wanted to have a central class for communicating with the ML-Predictor(python code) and share the results with each of the extractors. Do know of a better way/have a suggestion on how I could solve this problem?

**Comment by lucaro** [comment]
I guess the ideal solution would be if you could export your prediction models in such a way which would enable you to call them directly via a java class. In case this is not possible, the next best thing would be to use a remote procedure call framework to expose your (python) logic to the java classes. We use gRPC for the communication between cottontail db and cineast for example. If this is also not feasible, it would probably be easier to implement an exporter in cineast, which exports your media items together with the relevant metadata in a format you can use in your python code. Then you can run the predictors independently and subsequently import the your results back into cineast.

**Comment by cribin** [comment]
I think using gRPC for communication could be an option. Thanks for the suggestions, I will try it out.
