### ISSUE TITLE
Communicating with the cineast api via Rest

### ISSUE THREAD

**Issue by RibinMTC** [vitrivr/cineast#153]
Dear devs,

Is it possible to communicate with the cineast api via REST or is only gRPC supported, i.e. could I send REST commands from a python client to the cineast api?

Best,

Ribin

**Comment by lucaro** [comment]
Yes, cineast has a REST api. It is even OpenAPI compliant, so you don't even need to build your client endpoints by hand. Just have a look at https://github.com/vitrivr/cineast/blob/master/cineast-api/src/main/java/org/vitrivr/cineast/api/APIEndpoint.java

**Comment by RibinMTC** [comment]
Thanks!
