### ISSUE TITLE
Inserting into a table with multiple feature columns

### ISSUE THREAD

**Issue by RibinMTC** [vitrivr/cineast#159]
Dear devs,

I want to have a table with multiple feature columns(feature_1, feature_2,...). But when I tried to insert into cottontail, I received the following message: _"INVALID_ARGUMENT: Insert failed because data validation failed: Insert failed because column feature does not exist in entity"_. Does that mean I have to have a column named "feature"?

Best,

Ribin

**Comment by lucaro** [comment]
Could you please provide more information on this: how did you create the entity? how exactly are you trying to insert entries into the entity?

**Comment by RibinMTC** [comment]
1) I created the entity by defining a custom extractor class(which implements the Extractor interface). I call the following method: `@Override
    public void initalizePersistentLayer(Supplier<EntityCreator> supply) {
        supply.get().createFeatureEntity(tableName, true, columnNameAndType);
    }`
Here the variable _columnNameAndType_ contain the name and type of the features. 

2) I insert the entries during the cineast extraction process, by specifying my custom extractor in the job file.

Now I see that maybe I should have used the _createEntity_ method instead of _createFeatureEntity_ method :) ?

**Comment by lucaro** [comment]
`EntityCreator.createFeatureEntity` will create an entity with an `id` and a `feature` column, since this is the usual layout. If you want to customize your entity, you will indeed have to use `EntityCreator.createEntity` (or `EntityCreator.createIdEntity`, so you don't need to manually specify the `id` column).
