### ISSUE TITLE
Holistic review and cleanup of REST Api / OAS

### ISSUE THREAD

**Issue by sauterl** [vitrivr/cineast#163]
After merge of #161 and #162 , as well as https://github.com/vitrivr/vitrivr-ng/pull/57 and https://github.com/vitrivr/vitrivr-ng/pull/54 a holistic review and cleanup of the REST api is due.

In particular, reviewing the OpenApi Specification (OAS) of Cineast and the process on how it is included in vitrivr-ng (see https://github.com/vitrivr/vitrivr-ng/pull/54 as well as enforcinig consistency in naming of endpoints:

- [ ] Review OAS completeness
- [ ] Review OAS client code generation process
- [ ] Review endpoint naming
- [ ] Implementation of above
- [ ] Cleanup of REST Api

Shall be resolved in coordination with https://github.com/vitrivr/vitrivr-ng/issues/58

**Comment by silvanheller** [comment]
See my comment in https://github.com/vitrivr/vitrivr-ng/issues/58 - this issue is ready to be tackled

**Comment by sauterl** [comment]
After some analysis I came up with [this changelog](https://gist.github.com/sauterl/1810e62cdc7409d6c482b5ac50bcb168) (read: these tasks), which I will address

**Comment by sauterl** [comment]
This is a larger endeavour than originally expected and requries more planning than feasably possible within an issue.
Please refer to this discussion: https://github.com/vitrivr/cineast/discussions/176
