### ISSUE TITLE
Specify which Metadata should be fetched when executing a query

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cineast#166]
Currently, Cineast fetches all available metadata for objects & segments when executing a query. This can add significant overhead (sample measurement for a tag query: tag query, 5s, 30k results, object metadata 400ms, segment metadata 5s). Sometimes this metadata is only technical, sometimes it is only desirable to fetch part of the metadata (e.g. LSC). I’d suggest adding the following to the queryconfig:
- an ALL option so clients can remain agnositic to metadata structure
- a list of metadata domains
- a list of metadata domain + key combinations

**Comment by sauterl** [comment]
This is a very good idea, which is partially already thought about in the unity interface, a client solely relying on cineast's REST API

**Comment by silvanheller** [comment]
Cottontail now has Unit-Tests to make sure that this is supported: https://github.com/vitrivr/cottontaildb/pull/76 and https://github.com/vitrivr/cineast/commit/83960ff2c67c4ec0fb6d132ceb17b2d6fa0ccdeb adds a method to explicitly only select certain columns from a table to the `DBSelector`.
