### ISSUE TITLE
Persisting a vector of strings 

### ISSUE THREAD

**Issue by RibinMTC** [vitrivr/cineast#169]
Dear devs,

For a given segment I produce a vector of strings. Does cineast support storing this vector to the cottontail db?  If yes, could you point me to an example? I have seen that there is vector support for _ReadableFloatVector_, but could not find something similar for strings.  Otherwise, should I have multiple database entries for each vector element?

Best,

Ribin

**Comment by lucaro** [comment]
Hey, string vectors are not supported. If you want to store multiple strings, you would need to explicitly create a 'column' for each.
For something different: we recently enabled github discussions for all main repos of the vitrivr organization, they are a more suitable place for questions.

**Comment by silvanheller** [comment]
I'll just briefly add: You can use Text Retrieval in Cottontail, check out for example how we search OCR. As @lucaro said though, feel free to start a discussion on the discussions page.
