### ISSUE TITLE
Conversion of JAVA code into KOTLIN. 

### ISSUE THREAD

**Issue by devmalik7** [vitrivr/cineast#181]
I would like to work on this issue .

**Comment by silvanheller** [comment]
Hi @devmalik7 and welcome to vitrivr! Re-writing the Cineast Codebase in Kotlin is currently not on our roadmap as it would require both large implementation as well as theoretical efforts. If you have concrete suggestions on things you'd like to rewrite in Kotlin, feel free to use the Discussions feature of Github on our repos.
