### ISSUE TITLE
Update Feature Documentation

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cineast#190]
The current [List of Features](https://github.com/vitrivr/cineast/wiki/Feature-Modules) could use a fresh pair of eyes and is a great way to get a feel for the different kind of features available for multimedia retrieval. To get a theoretical background and if you have an academic background, feel free to also read the [corresponding dissertation](https://edoc.unibas.ch/66289/), specifically chapters 4 and 7.

There are two ways you can contribute:

- By adding to the wiki, see #188 on further instructions
- By extending the documentation in the `feature` package of the classes where these Features are Implemented.

**Comment by Liuhaai** [comment]
Hi Silvan, Could I take on this documentation updating work?

**Comment by silvanheller** [comment]
Sure, feel free to get started

**Comment by Liuhaai** [comment]
> Sure, feel free to get started

Some new entries of Cineast features have been added into the table according to the description from [the book](https://edoc.unibas.ch/66289/) and WIKI page.
Here is the [updated markdown file](https://github.com/Liuhaai/Cineast-API/blob/master/Feature-Modules.md).

**Comment by Spiess** [comment]
Thanks @Liuhaai, I have merged your changes into the wiki.
There are still a few undocumented features marked with TODO that you can fill in if you want.

**Comment by lucaro** [comment]
Why are there features labelled with *Removed* ? If these modules no longer exist, just drop them from the list.

**Comment by Spiess** [comment]
Fair point, I have done so now.

**Comment by silvanheller** [comment]
Thanks @Spiess and  @Liuhaai !

**Comment by Liuhaai** [comment]
@Spiess Thanks for the work!
I have updated some entries of the table. Some un-existed features and non-feature entries are removed. I will continue to update this feature table if I can spare some time later.
Here is the [change](https://github.com/Liuhaai/Cineast-API/blob/master/Feature-Modules.md):

Remove:
- Contrast
- DailyCollectionBooleanRetriever
- DailyRangeBooleanRetriever
- OCRSearch
- RangeBooleanRetriever

Update:

- all “audio sample” are replaced with "audio frame"

- AverageColorGrid8Reduced11
- AverageColorGrid8Reduced15
- AverageColorRasterReduced11
- AverageColorRasterReduced15
- CLDReduced11
- CLDReduced15
- Lightfield
- LightfieldFourier
- LightfieldZernike
- MFCCShingle
