### ISSUE TITLE
Expand DBBooleanIntegrationTest

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cineast#192]
The current `org.vitrivr.cineast.core.db.DBBooleanIntegrationTest` only tests a subset of possible invocations of the `DBSelector` class. Possible extensions include:
- Testing the `getRowsAND` method with different conditions
- More tests for the different `RelationalOperator` values

Note: Currently only available on the `new-cottontail-api` branch, see #182

**Comment by Liuhaai** [comment]
Is `DBBooleanIntegrationTest` a Java file? it seems to do not exist in current project.

**Comment by silvanheller** [comment]
> 
> 
> Is `DBBooleanIntegrationTest` a Java file? it seems to do not exist in current project.

Currently only available on the `new-cottontail-api` branch, i've updated the issue
