### ISSUE TITLE
Fail to pass the building step of PR check

### ISSUE THREAD

**Issue by Liuhaai** [vitrivr/cineast#198]
[My PR](https://github.com/vitrivr/cineast/pull/197/checks) for Cineast fails to pass the building step. The bot said "The job running on runner Hosted Agent has exceeded the maximum execution time of 360 minutes." The change of PR is small. What is the possible cause of this problem?

**Comment by silvanheller** [comment]
Hey, we're not sure what the problem is #195 is also currently stuck. We'll have a look at the PR locally.
