### ISSUE TITLE
Switch publishing system

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cineast#208]
We should use a different plugin to publish our jars so we can upgrade to Gradle 7. See [Gradle Docs](https://docs.gradle.org/6.7.1/userguide/upgrading_version_5.html#legacy_publication_system_is_deprecated_and_replaced_with_the_publish_plugins). Additionally, it seems that v3.2.0 has broken the jar publishing process (see CI status)

**Comment by Spiess** [comment]
Judging by the CI status, this was fixed by #253.
