### ISSUE TITLE
Fix raw type issues with PersistentTuple and PersistencyWriter

### ISSUE THREAD

**Issue by lukasbeck** [vitrivr/cineast#22]
`PersistentTuple` is often used as a raw type across the whole project. Either narrowing down where `PersistentTuple` is used could help fix this problem or maybe reworking the type and class definitions of these classes.

**Comment by lucaro** [comment]
This is a known issue and a consequence of the architecture in combination with certain limitations inherent within the java generics system. To overcome this issue, it is probably required to re-implement `PersistencyWriter`, possibly without a generic `PersistentTuple` type.

**Comment by lucaro** [comment]
Fixed with changes introduced in https://github.com/vitrivr/cineast/commit/65c8ca31227700992d48713d2a20a89af12fc699
