### ISSUE TITLE
Feature extraction unsupported on macOS aarch64

### ISSUE THREAD

**Issue by Spiess** [vitrivr/cineast#225]
While there are no macOS aarch64 builds of the [JavaCPP Presets](https://github.com/bytedeco/javacpp-presets), image, video and audio feature extraction relying on FFmpeg is unsupported.

The relevant issue can be found here: https://github.com/bytedeco/javacpp-presets/issues/1069

**Comment by saudet** [comment]
I've introduced `macosx-arm64` builds for FFmpeg in commit https://github.com/bytedeco/javacpp-presets/commit/e38c9d192505b76227acb8a645a405e986bfc696.
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by Spiess** [comment]
I have tested the new FFmpeg snapshot on macOS aarch64 and they appear to be working great.

#247 should be mergeable with the definitive ffmpeg-platform 5.0-1.5.7 release.
