### ISSUE TITLE
ObjectInstances feature not implemented

### ISSUE THREAD

**Issue by Spiess** [vitrivr/cineast#266]
The [ObjectInstances](https://github.com/vitrivr/cineast/blob/master/cineast-core/src/main/java/org/vitrivr/cineast/core/features/ObjectInstances.java) feature exists as a Java class, but is not yet implemented.
In addition, its proposed functionality is not documented.

**Comment by lucaro** [comment]
I honestly don't remember what the idea behind this was, we can probably just delete it.

**Comment by silvanheller** [comment]
You can remove it
