### ISSUE TITLE
Max results are not respected for text retrieval

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cineast#308]
Searching e.g. for ASR results in way too many results from cottontail (V3C2 520k results instead of the configured value)

**Comment by lucaro** [comment]
I just checked and the row limit appears indeed to be ignored in the `CottontailSelector`, see https://github.com/vitrivr/cineast/blob/dcdc208595d72b865faa3ec650fd4e99874a4269/cineast-core/src/main/java/org/vitrivr/cineast/core/db/cottontaildb/CottontailSelector.java#L343

**Comment by silvanheller** [comment]
Fixed in #312
