### ISSUE TITLE
Allow extraction without DB connection

### ISSUE THREAD

**Issue by x4e-jonas** [vitrivr/cineast#384]
Cineast refuses to start without a database connection. Even if you just want to extract [something to JSON](https://github.com/vitrivr/cineast/wiki/Extraction-Configuration#database) files using the CLI and with the API disabled it forces you to run a database.

My use case is to only run extraction on one instance and import the JSON on another instance.

**Comment by x4e-jonas** [comment]
Setting the selector to `NONE` instead of `JSON` worked for me. I think [the documentation here](https://github.com/vitrivr/cineast/wiki/Extraction-Configuration#database) is not very clear.

**Comment by sauterl** [comment]
The [documentation](https://github.com/vitrivr/cineast/wiki/Extraction-Configuration#database) has been updated accordinlgy.
