### ISSUE TITLE
 Schema 'warren.cineast' does not exist

### ISSUE THREAD

**Issue by akohlbecker** [vitrivr/cineast#387]
This seems to be a regression of #255.

To reproduce clone https://github.com/akohlbecker/vitrivr-docker-compose

and start the vitrivr stack with docker compose:

~~~bash
docker compose up --build 
~~~

conttontaildb startup fails with:

~~~
cineast     | 2024-04-17 16:08:41.046 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at cottontail:1865
cottontail  | Cottontail DB server is up and running at port 1865! Hop along... (catalogue: V3_1, pid: 7)
cineast     | 2024-04-17 16:08:41.199 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 153 ms at cottontail:1865
cottontail  | 2024-04-17 16:08:41 [DefaultDispatcher-worker-1] DEBUG TransactionalGrpcService:135 - [1, c1068fd9-5dd0-4cea-b725-8082c3c98efd] Preparation of AboutEntity completed successfully in 35.994953ms.
cottontail  | 2024-04-17 16:08:41 [DefaultDispatcher-worker-1] ERROR TransactionalGrpcService:225 - [1, c1068fd9-5dd0-4cea-b725-8082c3c98efd] Execution of AboutEntity query failed: Schema 'warren.cineast' does not exist!
cottontail  | 2024-04-17 16:08:41 [DefaultDispatcher-worker-1] ERROR TransactionalGrpcService:226 - org.vitrivr.cottontail.dbms.exceptions.DatabaseException$SchemaDoesNotExistException: Schema 'warren.cineast' does not exist!
~~~

**Comment by lucaro** [comment]
I'm not sure what behavior you are expecting here. I had a quick look at your docker comose and could not find a database initialization step anywhere. Just based on the log snippet, it's also not quite clear if you interacted with cineast in any way that would cause it to query an uninitialized database. Could you elaborate on what you were trying to do?

**Comment by akohlbecker** [comment]
In the wiki (https://github.com/vitrivr/cineast/wiki/Environment-Setup & https://github.com/vitrivr/cottontaildb/wiki ) I did not find anything on initializing a db, therefore I was assuming that cineast has a default configuration that allow it to connect cottontaildb in order to initialize a DB in case it is missing.

**Comment by lucaro** [comment]
Well, the features based on which retrieval is performed need to come from somewhere. Generally, cineast extracts them and stores them in cottontaildb. Since the features to be used are configurable, the relevant database initialization happens only when the features are used for extraction. See https://github.com/vitrivr/cineast/wiki/Extracting-Features#extracting-directly-to-cottontail-db.

**Comment by akohlbecker** [comment]
Thanks a lot! That answers two of the questions I scratch my head about.

**Comment by lucaro** [comment]
Ok great. If you have any further questions, please don't hesitate to reach out through the [Discussions](https://github.com/vitrivr/cineast/discussions) tab.
