### ISSUE TITLE
MultimediaObjectDescriptor Naming

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cineast#42]
getObjectID() is misleading in that it returns <type>_<objectid> for the ProtoWriter / Selector

**Comment by lucaro** [comment]
This issue is unclear to me, could you please elaborate?

**Comment by silvanheller** [comment]
Sorry, github formatting ate the relevant parts (`<>` causes content to disappear...). getObjectID() returns `<type>_<object>` and not just `<object>` - unless the ObjectID is  `<type>_<object>` and i misunderstood our offline discussion as in #41

**Comment by lucaro** [comment]
For all practical purposes, `<type>_<object>` is the 'objectID', even though there should never be two objects of different types which have the same `<object>` part.
