### ISSUE TITLE
JsonSelector breaks for MedianColor

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cineast#43]
`{"id":"i_CuMWCPS6D3hnTmwA_1","feature":[100,-0.04735537,-0.010409119]}`

starts with an Integer, so `PrimitiveTypeProvider.fromObject` tries to generate an Integer-Array. This throws a ClassCastException since you can't cast Doubles to Integers.

This is fixed for me (44f4a05aaf2da23338349b8947e9a28ce3da9f07) and JSON isn't used in production as far as I'm aware but I'll leave this here as a reference for maybe a future PR. (JSON has other issues which I'm fixing as-i-go on the evaluation branch)

**Comment by lucaro** [comment]
Fixed by merging Pull Request #44
