### ISSUE TITLE
[Wishlist] Filter Metadata

### ISSUE THREAD

**Issue by sauterl** [vitrivr/cineast#63]
It would be very convenient if one could filter metadata domains at request-time:

To illustrate the aforementioned feature, let's have a look to the following example: 

When requesting metadata of several objects (for RESTful API), the request to `/api/v1/find/metadata/by/id` would may be look like:

```
{
  "filters": [
   "LOCATION, "JSON"
   ],
  "ids":[
    "i_zD0BXwe4a7ljNbRJ",
    "i_1bBhZC4JLdf7RGKL"
  ]
}
```

The response would only contain metadata entries of the domains `LOCATION` and `JSON`

**Comment by silvanheller** [comment]
#68 seems to resolve this
