### ISSUE TITLE
[Wishlist] Sophisticated Metadata API

### ISSUE THREAD

**Issue by sauterl** [vitrivr/cineast#64]
As an attendum to #63 

In general more cineast-side filtering / processing of metadata would be highly appreciated:
This includes, but is not limited to:

 * specify domain on request-time (see #63 )
 * specify domain and key in the request (e.g. for a GET request: `api/v1/metadata/of/:objectID/:domain/:key` )
 * by domain (e.g. for a GET request: `api/v1/metadata/in/:domain` )
 * by key, regardless domain (e.g. for a GET request: `api/v1/metadata/with/:key`)

**Comment by silvanheller** [comment]
#68 seems to resolve this
