### ISSUE TITLE
Inconsistency in RESTful API response

### ISSUE THREAD

**Issue by sauterl** [vitrivr/cineast#69]
As seen in https://github.com/vitrivr/cineast/blob/a8180adea7e8dca2ecab24f760fadd2958a69d20/src/org/vitrivr/cineast/api/rest/handlers/actions/FindTagsActionHandler.java#L28,
a request to `/api/v1/find/tags/all` results in a top-level array, whereas in every other response I know (may be there are more inconsistencies), the response is an object, containing the actual query result.

EDIT: The API responses _once_ consisted of top-level objects.
Nevertheless, this inconsistency is rather inconvenient: Sometimes the response is an object, sometimes an array - I suggest to only use objects, as some JSON parsers do not support top-level arrays.
Furthermore, the WebSocket API always returns top-level objects, which is another reason for the same behaviour in the RESTful API.

**Comment by silvanheller** [comment]
Is this still an issue in the new API @sauterl ?

**Comment by sauterl** [comment]
@silvanheller As far as I'm aware, I fixed all these things in #120

**Comment by sauterl** [comment]
As seen in https://github.com/vitrivr/cineast/blob/771bd3d90a3aa8509ad73f2bbcd17cf0ed397e54/cineast-api/src/main/java/org/vitrivr/cineast/api/rest/handlers/actions/tag/FindTagsAllGetHandler.java#L21 this was definitely fixed in #120 and thus, this issue is closed.
