### ISSUE TITLE
issue while running ./gradlew deploy 

### ISSUE THREAD

**Issue by Yashwanth711** [vitrivr/cineast#74]
* What went wrong:
Could not determine java version from '11.0.1'.
 
I got this issue while building .

**Comment by Yashwanth711** [comment]
i changed the gradle version 2.12 to 5.0 
even though there is problem


FAILURE: Build failed with an exception.

* Where:
Build file '/home/yashu/cineast/build.gradle' line: 217

* What went wrong:
A problem occurred evaluating root project 'cineast'.
> Could not find method leftShift() for arguments [build_9j0s2dibt6nq9ibpy9e7uig4$_run_closure11@3a3f2da1] on task ':copyResources' of type org.gradle.api.DefaultTask.

**Comment by lucaro** [comment]
The cineast master branch is currently not compatible to java 11. If you need to run cineast in a java 11 environment, switch to the dev branch.
