### ISSUE TITLE
Library for Cineast interaction

### ISSUE THREAD

**Issue by NickFitton** [vitrivr/cineast#75]
Currently, to interact with the jar, the dependent needs to write configurations that mimic the config in Cineast.
To smooth out updating 3rd parties, there should be a cineast-api, deployed to gradle or otherwise that 3rd parties can use.

**Comment by lucaro** [comment]
How would you imagine this to work exactly?

**Comment by NickFitton** [comment]
The cineast repo is split into submodules:
* cineast-api
  * Which consists of what are currently config classes
  * This is what could be used by 3rd parties
* cineast-core
  * Which uses the config classes just like normal

**Comment by ppanopticon** [comment]
Hey!

We're currently working on the modularization of Cineast in the branch 'multi-module'. Feel free to review and contribute.

**Comment by lucaro** [comment]
This is currently being implemented on the dev branch and will be part of the next release.
