### ISSUE TITLE
QoL: Re-add direct commands

### ISSUE THREAD

**Issue by sauterl** [vitrivr/cineast#81]
As of now (branch `multi-module`) _the old way_ of calling a certain functionality (e.g. start an extraction job) is not supported anymore: One has to manually type the command in cineast's CLI:

It would be nice to have those direct commands back, e.g.

Instead of:

**currently**:

```
java -jar cineast.jar cineast.json
cineast>extract -e path/to/config.json
```

**supposetly in future**:

```
java -jar cineast.jar cineast.json extract -e path/to/config.json
```

**Comment by silvanheller** [comment]
This is possible with the fat jar

```
./gradlew cineast-api:fatJar
java -jar cineast.jar cineast.json ...
```

All commands after that correctly go to the cineast cli
