### ISSUE TITLE
[Bug] No default config in code

### ISSUE THREAD

**Issue by sauterl** [vitrivr/cineast#82]
On branch `multi-module` there is no default config in code
This leads -if one config is not explicitely given- to a crash.

In the case of a missing cache config, this leads to a failure due to no default cache config is used.

Also, in the example config, there is no cache mentioned.

**Comment by sauterl** [comment]
@lucaro @silvanheller @ppanopticon Is there a reason for not using the default values in [CacheConfig.java:25](https://github.com/vitrivr/cineast/blob/multi-module/cineast-core/src/main/java/org/vitrivr/cineast/core/config/CacheConfig.java#L25) ?

**Comment by silvanheller** [comment]
Fixed on dev, if there are issues with config-defaults please open a separate issue
