### ISSUE TITLE
[Discussion] Versioning

### ISSUE THREAD

**Issue by sauterl** [vitrivr/cineast#83]
Since the only release of cineast is [v2.0.0](https://github.com/vitrivr/cineast/releases/tag/2.0.0), I suggest to state the versioning scheme in the README.

**Comment by sauterl** [comment]
I personally would suggest to use [semver](https://semver.org).

**Comment by lucaro** [comment]
All components of the vitrivr stack have been using semver since v1.0. Due to the low number of actual releases, this is however not obvious.
