### ISSUE TITLE
[Discussion] Code style

### ISSUE THREAD

**Issue by sauterl** [vitrivr/cineast#84]
I think we should agree on a code style to use.
Obviously, as it is very common I would suggest to use [Google's codestyle](https://google.github.io/styleguide/javaguide.html)

**Comment by lucaro** [comment]
Cineast has been (primarily) using the google code style for many years. This has however never been enforced and therefore the styling is not always consistent...

**Comment by sauterl** [comment]
Resloved by 2cd879d

**Comment by silvanheller** [comment]
There's a code style file in `docs/`... though that should maybe be added to the readme

**Comment by lucaro** [comment]
We can also have a gradle task which checks the code style. Though I would not add such a task to the dependencies of build, as it probably slows down the process quite a bit...
