### ISSUE TITLE
Release Management Automation

### ISSUE THREAD

**Issue by lucaro** [vitrivr/cineast#89]
Since the last release, nobody updated the pre-built version of the UI in the github releases. Could someone have a look at this and how to prevent this in the future?

**Comment by silvanheller** [comment]
What should the release artifact include? just jar and config-file? Or the entire source code? One way to prevent this is to have a PR template.

**Comment by lucaro** [comment]
Ideally, there would be a pre-built version for every component of the stack which is known to be compatible to each other. This is especially relevant for the UI (see https://github.com/vitrivr/vitrivr-ng/issues/15 where I copied this from) since having a jdk when you have a jre is probably more likely than having a node environment. We could then link all these released components together on a page on vitrivr.org.

**Comment by silvanheller** [comment]
The current state is that we'd like two things: 
- Automatically update `latest` on Dockerhub (See [Github Actions](https://docs.github.com/en/actions/language-and-framework-guides/publishing-docker-images)
- Automatically build & publish releases (always / for certain versions)

**Comment by silvanheller** [comment]
Thanks @mpas97!
