### ISSUE TITLE
Remove / Re-introduce Benchmarking Config

### ISSUE THREAD

**Issue by lucaro** [vitrivr/cineast#94]
Since the restructuring, the benchmarking config is not used properly, since it would introduce a dependency from core to standalone. This needs some redesign in order to be useful again.

**Comment by silvanheller** [comment]
Is there documentation on the desired functionality of the benchmarking config somewhere?

**Comment by lucaro** [comment]
This component was introduced by @ppanopticon in order to measure the required time of all the steps required for retrieval. The relevant logic is implemented around https://github.com/vitrivr/cineast/blob/dev/cineast-core/src/main/java/org/vitrivr/cineast/core/config/BenchmarkConfig.java There is currently however apparently no way to pass such a config when cineast is used as a standalone application if I'm not mistaken.
