### ISSUE TITLE
Large Files

### ISSUE THREAD

**Issue by lucaro** [vitrivr/cineast#97]
I recently moved the larger resource files, such as BoW codebooks and DNN weights to git lfs but as it turn out this quickly maxes out the github bandwidth limit. So we should come up with a workflow which enables us to host these larger files somewhere else and easily download them when necessary. I'm doing something like this for https://github.com/lucaro/VideoSaliencyFilter, but here we have more files which have to be managed. Thoughts?

**Comment by silvanheller** [comment]
Suggestion 1: We can use vitrivr.org/.../... as url and then download the files via setup-script or gradle at setup-time (preference for gradle). This would use dbis-server space, but if vitrivr.org moves to another server in the future, this solution would not break backward compatibility. If, at some point we want to provide a release-jar or zip in the future, this solution would also fit.

**Comment by lucaro** [comment]
I agree that this would be the best way to go, but the devil is in the details. If we implement this, we need to define 1. how the client knows which files to download from the server and 2. how a developer can put files onto the server. The first part is probably easiest handled by a versioned file which lists URLs and target paths relative to the project root. The second is a workflow question that needs to be discussed.

**Comment by lucaro** [comment]
I implemented the external download mechanism in efb8ef6ba152c7b6171b8f2faa4a9a5192f75075. Now we just need to figure out an efficient way to manage the files on that server...

**Comment by lucaro** [comment]
Closing this for now, as we currently have a workable, if not perfect solution.
