### ISSUE TITLE
Websocket-Message Size seems to be magically capped around 6500 string length in Safari

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cineast#98]
For some queries, the base64-string sent by vitrivr-ng is cut at ca. 6k string length when it arrives at cineast. This then leads to two issues: 1) the query is not executed since the message cannot be parsed properly. 2) the ws-connection crashes, jetty closes it with a 1006 error (which is not helpful at all).
I have not managed to triangulate the issue, none of the available config-parameters from jetty fix the problem and it also does not seem to be a problem on the vitrivr-ng side. 

This is not a clearly reproducible problem, it is most probably reproduced by drawing a small black circle. 

This is certainly an issue for novices, as we have neither automatic reconnect nor is it intuitive if a query is not executed.

One trivial fix would be to resize the canvas before serialization in vitrivr-ng from currently 450x450 to e.g. 200x200. This would reduce the length of the base64-string without a massive reduction in the quality of sketch input and would be very low implementation effort.

Thoughts @lucaro?

**Comment by lucaro** [comment]
This does not sound like correct behavior to me since 6k is a rather arbitrary limit. It is however most certainly not something to do with cineast itself but rather with the embedded web server it uses. This needs further investigation. I guess reducing the canvas resolution might be a necessary evil for now until we can see how to fix this properly...

**Comment by lucaro** [comment]
@silvanheller I was not able to reproduce the problem in order to trace it. Could you provide an image which triggers this behavior?

**Comment by silvanheller** [comment]
Anything like this does the job on Safari, but not on Chrome / Firefox (where the same circle is serialized to approx. ~13k / 6k message size, both of which arrive without any issue at cineast). So it is most likely a Safari problem. However, i think i've encountered the problem already on chrome / firefox. It seems also to depend on the size of the sketched circle, small circles do not crash.
![Screen Shot 2019-12-19 at 09 22 56](https://user-images.githubusercontent.com/14314470/71156879-34117780-2241-11ea-86f3-e0d3b52f07ac.png)
I suggest keeping this issue open in case someone can reproduce it on firefox / chrome

**Comment by lucaro** [comment]
If I remember correctly, we had problems with Safari in the past. I for one never considered it to be an 'officially supported browser' so if the issue only manifests itself there, I don't see it as a high priority one as it can be easily avoided by using another browser. We should however keep an eye on this, especially in the context of the planned OpenAPI-related changes.

**Comment by silvanheller** [comment]
I could not reproduce this bug anymore after the migration to OpenAPI
